# Generated by Django 4.0 on 2021-12-13 16:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=20)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('edge_detection_votes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=1)),
                ('contour_detection_votes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=1)),
            ],
        ),
    ]
